version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  backend:
    build:
      context: todo-backend
      args:
        UID: ${UID:-1001}
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db:db
    user: rails
  frontend:
    build:
      context: todo-frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - "3000:3000"
    user: frontend

